proyecto_pools/django_crud_venv/agenda/agenda/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('agendapersonal/', include('agendapersonal.urls')),
    path('admin/', admin.site.urls),
]

proyecto_pools/django_crud_venv/agenda/agendapersonal/urls.py
from django.contrib import admin
from django.urls import path

from agendapersonal import views

app_name = 'agendapersonal'
urlpatterns = [
    path('', views.Index.as_view(), name = 'index'),
    path('<int:pk>/', views.VistaDetalles.as_view(), name ='detalles')
]

proyecto_pools/django_crud_venv/agenda/agendapersonal/models.py
from django.db import models

class Entrada (models.Model):
    titulo = models.CharField(max_length=25)
    texto = models.CharField(max_length=300)
    fecha_creacion = models.DateTimeField('fecha_creacion')

    def __str__(self):
        return self.titulo


class Actualizacion (models.Model):
    tipo = models.CharField(max_length=10)
    fecha = models.DateField('fecha')
    hora = models.TimeField('hora')
    entrada = models.ForeignKey(Entrada, on_delete=models.CASCADE)

    def __str__(self):
        return self.tipo

proyecto_pools/django_crud_venv/agenda/agendapersonal/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Entrada, Actualizacion

class Index(generic.ListView):
    template_name = 'agendapersonal/index.html'
    context_object_name = 'latest_entrada_list'

    def get_queryset(self):
        return Entrada.objects.order_by('fecha_creacion')


class VistaDetalles(generic.DeleteView):
    model = Entrada
    template_name = 'agendapersonal/detalles.html'

proyecto_pools/django_crud_venv/agenda/agendapersonal/templates/agendapersonal/detalles.html
{% csrf_token %}
<fieldset>
    <legend><h1>{{ entrada.titulo }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <p> {{entrada.texto}}
</fieldset>

proyecto_pools/django_crud_venv/agenda/agendapersonal/templates/agendapersonal/index.html
{% load static %}

{% if latest_entrada_list %}
    <ul>
    {% for entrada in latest_entrada_list %}
        <li><a href="{% url 'agendapersonal:detalles' entrada.id %}">{{ entrada.titulo }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}